var lang;
if(navigator.language.startsWith('zh')){
    lang=[
        '控制器模式',
        '键盘 / 鼠标',
        '游戏手柄',
        'e-AMUSEMENT CLOUD (更改后需要重新连接)',
        '键绑定',
        '宏按键按下操作',
        '宏按键长按操作',
        '宏 PIN',
        '启用 LED',
        'LED 亮度',
        'HID 灯效',
        '按键灯效',
        'BT 颜色',
        'FX 颜色',
        'START 颜色',
        'Tool To Key',
        '启用旋钮灯',
        'VOL-L 颜色',
        'VOL-R 颜色',
        '灯光模式',
        '关闭',
        '单色',
        '呼吸',
        '渐变',
        '单色 / 呼吸颜色',
        '欢迎使用 ALL Voltex Controller 设置',
        '未选择设备',
        '正在连接设备...',
        '已连接，正在选择选项...',
        '无效设备',
        '正在下载固件...',
        '正在安装固件...',
        '完成!',
        '正在准备界面...',
        '已连接！',
        '发现 ALL Voltex Controller v',
        '需要升级固件，设备将会重启，请重新连接以升级',
        '需要升级固件，请重新连接以进行升级',
        '重新启动至引导加载程序，配置读取中止',
        '设备未连接',
        '重置设置无法恢复，确定继续？',
        '正在断开连接...',
        '重置设置',
        '设备已断开连接',
        '操作',
        '按下按键',
        '宏 PIN',
        '切换灯光模式',
        '开启 / 关闭 LED',
        '按键',
        '无',
        '连接',
        'ALL Voltex Controller - 设置'
    ]
}
else{
    lang=[
        'Input mode',
        'Keyboard/Mouse',
        'Joystick',
        'e-AMUSEMENT CLOUD (reconnect after change)',
        'Keyboard bindings',
        'Macro click',
        'Macro longpress',
        'Macro PIN',
        'Enable LEDs',
        'LED Brightness',
        'HID Lights',
        'Key lights',
        'BT colour',
        'FX colour',
        'START colour',
        'Tool To Key',
        'Knob lights',
        'VOL-L colour',
        'VOL-R colour',
        'Lights pattern',
        'None',
        'Solid',
        'Breathe',
        'Follower',
        'Solid/Breathe colour',
        'Welcome to the ALL Voltex Controller Configurator',
        'No device selected',
        'Opening device...',
        'Opened, selecting configuration...',
        'Invalid device found, is this a Tatacon converter?',
        'Downloading fimware...',
        'Flashing firmware...',
        'Done!',
        'Selected, claiming interface...',
        'Opened!',
        'Found ALL Voltex Controller v',
        'Firmware update required. Device will be rebooted. Connect again to update',
        'Firmware update required. Connect again to update',
        'Rebooted to bootloader, config read aborted',
        'Device not opened',
        'Loading defaults cannot be undone. Are you sure?',
        'Closing device...',
        'Load defaults',
        'Device disconnected',
        'Action',
        'Keypress',
        'Macro PIN',
        'Cycle LED pattern',
        'Toggle LEDs',
        'Key',
        'None',
        'Connect',
        'ALL Voltex Controller - Config'
    ]
}